### PR TITLE
Make `git` command run in correct directories (fixes #428).

### LINKED ISSUE #428: fatal: not a git repository error when updating any plugins
**Describe the bug**
When I do zinit update, when it comes to updating the plugins I get the following error:

".fatal: not a git repository (or any of the parent directories): .git"

**To Reproduce**
Not sure, I just do zinit update, and get the error message as seen above

**Expected behavior**
Just update the git repos for the plugins without that error.

**Screenshots**
https://imgur.com/a/cMZIs5m

**Versions:**
 - $ZSH_VERSION == 5.7.1
 - Operating system name and version (uname -a): Linux pxm.eeleater.org 5.4.65-1-pve #1 SMP PVE 5.4.65-1 (Mon, 21 Sep 2020 15:40:22 +0200) x86_64 GNU/Linux

(But this also happens on any of my Systems, be it my work laptop with wsl, my proxmox server, or any of the vms on it)

**Additional context**
If needed, my dotfiles repo: https://git.eeleater.org/eeleater/dotfiles

### PR DESCRIPTION
**Pull request by tsukker**
Fix #428 .
I set draft as I didn't know how to test.

### CODE REVIEW

**Comment by AnimiVulpis** [comment]
The `main_branch` variable is used in exactly 3 places (as far as I saw).

One is in a part that is surrounded by an `if (( ! is_release )) {` conditional.


The second and third place are surrounded by `if [[ -d $local_dir/.git ]]; then` (line 1658) which basically makes sure that `$local_dir` is a git repository.
If I understand correctly the logic in this part would not work if the repo in question uses a `main` instead of a `master` branch (because it's not relying/checking the `is_release` variable).
Am I getting this right?

Do you where the error with not checking for `is_release` is coming from?
Is there a way to make that more specific?

_TBH I do not really understand the `is_release` variable and what it is used for_

**Comment by tsukker** [comment]
Sorry for the lack of explanation.

I guess `is_release` is true when the plugin directory is a *binary release* from GitHub Releases (gh-r), which is not a *git repository*.

The first condition `(( ! is_release ))` is added so that the `git` command of the second condition `git -C $repo show-ref --verify --quiet refs/heads/main` is not run in *binary release* directories.

Without checking `is_release`, `git` command can be executed in non-git (binary release) directory and cause the error `fatal: not a git repository`.

(When the target directory is a binary release, string `"master"` is assigned to `main_branch`, but this is not a problem.)

Now I think `if [[ -d $repo/.git ]] && git -C $repo show-ref --verify --quiet refs/heads/main; then` is easier to understand, while it gets the same result.

**Comment by AnimiVulpis** [comment]
@tsukker I like your improved solution and appreciate your explanation.

I hope this gets merged soon.

If nobody reacts to this PR in time (whatever that means. Don't want to bother them just because **I** think that this issue is urgent) I will check the reddit and IRC and ask around^^

**Comment by tsukker** [comment]
@AnimiVulpis 
I pushed the change.
And thanks for your kindness, tbh I'm not familiar with those services and don't know the manner..

**Comment by psprint** [comment]
Thanks for this PR. I've used it in a patch that fixes the issue. Thanks again.

**Pull request closed without merging**
